### ISSUE TITLE
pf-ring next iteration

### ISSUE THREAD

**Issue by alongir** [kubeshark/pf-ring-compiler#17]
Have users running on supported targets (e.g. AL2) be able to build an image and push the pf-ring image, assuming:
1. We add them to the project team
2. We accept their PR as the shouldn't be allowed to push directly.
3. Once PR is accepted an automatic process triggers that builds and pushes the PF-RING image.

Provide simply and short instructions set that can guide a user through the process.

**Comment by corest** [comment]
## How to add new PF_RING module into `kubeshark/pf-ring-module:all` image?

1. Get latest release of pf-ring-compiler for your platform here https://github.com/kubeshark/pf-ring-compiler/releases
2. Switch to proper Kubernetes context in the terminal.

Verify the access works with `kubectl version`

```
kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-eks-508b6b3
```

3. Run pfring-compiler for target platform (EKS in this case, which uses Amazon Linux 2)

```
pfring-compiler compile --target al2
{"level":"info","msg":"creating compile job default/al2-pf-ring-compiler","time":"2024-03-21T14:17:52+02:00"}
{"level":"info","msg":"compile job default/al2-pf-ring-compiler created","time":"2024-03-21T14:17:52+02:00"}
{"level":"info","msg":"waiting for compile job to start","time":"2024-03-21T14:17:52+02:00"}
{"level":"info","msg":"compile job started","time":"2024-03-21T14:17:54+02:00"}
{"level":"info","msg":"waiting for compile pod to start","time":"2024-03-21T14:17:54+02:00"}
{"level":"info","msg":"compile pod started","time":"2024-03-21T14:18:12+02:00"}
{"level":"info","msg":"waiting for compile job to complete pf-ring module compilation","time":"2024-03-21T14:18:12+02:00"}
{"level":"info","msg":"pf-ring module compilation completed","time":"2024-03-21T14:19:41+02:00"}
{"level":"info","msg":"copying kernel module to local fs","time":"2024-03-21T14:19:41+02:00"}
{"level":"info","msg":"kernel module copied to pf-ring-5.10.210-201.852.amzn2.x86_64.ko","time":"2024-03-21T14:19:43+02:00"}
{"level":"info","msg":"cleaning up compile job","time":"2024-03-21T14:19:43+02:00"}
```

As a result you will get module `pf-ring-5.10.210-201.852.amzn2.x86_64.ko` in current folder (the name has format `pf-ring-<kernel version>.ko`)

4. Clone pf-ring-compiler repository

```
git clone https://github.com/kubeshark/pf-ring-compiler
cd pf-ring-compiler
git checkout -b "add-module-<version>"
```

5. Copy kernel module from step 3 into `modules/ko` folder.
6. Commit your changes and submit the PR

```
git add modules/ko/pf-ring-5.10.210-201.852.amzn2.x86_64.ko
git commit -S -m "Add PF_RING module for kernel 5.10.210-201.852.amzn2.x86_64"
git push origin add-module-<version>
```

Create PR and wait for it to be reviewed/merged.
After the merge Github Action pipeline will build new `kubeshark/pf-ring-module:all` image.

**Comment by alongir** [comment]
@corest  So, this task is done? (if the git action works, then yes, right?)

**Comment by corest** [comment]
done
